<div class="block block-product-slider slider-list">
    <div class="block-title"><h2>List</h2></div>
    <div class="block-content">Product slider</div>
</div>
<?php $productCollection = $block->getLoadedProductCollection() ?>
<div	class="block	block-product-slider	slider-list">
    <div	class="block-title">
        <h2>List</h2>
    </div>
    <div	class="block-content">
        <?php if (count($productCollection)): 
           
        ?>
            <ul>
                <?php foreach ($productCollection as $product): 
                    $imageUrl =  $block->getUrl('pub/media/catalog').'product'.$product->getImage();?>
                    <li><img src="<?php echo $imageUrl ?>" width="220px" /><?php echo $product->getName() ?></li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
</div>